### ISSUE TITLE
Testes Junit

### ISSUE THREAD

**Issue by JoaoSilva2** [premium-minds/summer-internship-exercise-2021#6]
Bom dia, gostaria de saber se é permitido criar um novo ficheiro de testes Junit para testar um classe auxiliar que criei.

**Comment by amadoandre** [comment]
Boas , Sim claro

**Comment by ricardomorais3** [comment]
Para além de testar que o output calculado é o correcto, que outros aspectos é esperado que os JUnits testem?

**Comment by amadoandre** [comment]
É esperado que testem o que vos fizer sentido, claro que o output é sempre uma coisa boa de ser testada, mas podem testar outras coisas.

**Comment by JoaoSilva2** [comment]
Obrigado pela resposta. :+1:
